"""
Django settings for acmpx_proj project.

Generated by 'django-admin startproject' using Django 2.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

from .settings_base import *

# DEBUG = False

ALLOWED_HOSTS = ['localhost']

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.mysql',
		'NAME': 'acmpx',
		'USER': 'blue',
		'PASSWORD': 'test',
		'HOST': '',
		'PORT': '',
	}
}

# static 和 media 目录位置

STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# 项目实际运行时的域名，用于证书生成和证书中的查询网址

BASE_URL = 'http://localhost:8000'
